server {
    server_name midterm-app.store www.midterm-app.store;

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/midterm-app.store/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/midterm-app.store/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.midterm-app.store) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = midterm-app.store) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name midterm-app.store www.midterm-app.store;
    return 404; # managed by Certbot




}