services:
  web:
    image: hueminh2005/midterm-app:latest
    container_name: midterm-web
    restart: always
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/products_db
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      - mongodb
    networks:
      - midterm-network

  mongodb:
    image: mongo:6.0
    container_name: midterm-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=products_db
    volumes:
      - mongo_data:/data/db
    networks:
      - midterm-network

volumes:
  uploads_data:
  mongo_data:

networks:
  midterm-network:
    driver: bridge
